<template>
  <div>
    <h-list-new :dataSource="listData" v-on:HREVENT_itemClick="itemClick">
        <div slot="otherContent" slot-scope="props">
            <div class="detailList" v-for="(item,index) in props.otherContentList" :key="index" v-if="index <2">
                <strong>议案</strong>{{index+1}}： {{item.Dmpname}}
            </div>
            <div class="detailList" v-if="props.otherContentList.length>2">
                其它{{props.otherContentList.length - 2}}个议案&gt;&gt;
            </div>
        </div>
    </h-list-new>
  </div>
</template>

<script>
import { HListNew } from "vux";
export default {
    data() {
        return {
            listData: [
            {
                "title": "大额采购委员会2018年第3次会议",
                "processName": "大额采购委员会",
                "taskName": "草稿",
                "time": "2018-12-28 08:00:00",
                "otherContentList": [],
                "taskColor": "tab_lightblue"
            }, {
                "title": "职工代表大会暨工会会员代表大会2018年第10次会议",
                "processName": "职工代表大会",
                "taskName": "草稿",
                "time": "2018-12-19 08:00:00",
                "otherContentList": [],
                "taskColor": "tab_lightblue"
            }, {
                "title": "大额采购委员会2018年第2次会议",
                "processName": "大额采购委员会",
                "taskName": "草稿",
                "time": "2018-12-18 20:00:00",
                "otherContentList": [],
                "taskColor": "tab_lightblue"
            }, {
                "title": "业务审查委员会2018年第2次会议",
                "processName": "业务审查会",
                "taskName": "进行",
                "time": "2018-12-18 16:46:49",
                "otherContentList": [{
                    "totalnumber1": "1",
                    "totalnumber2": "1",
                    "Dmpid": 52511,
                    "Dmpname": "测试",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "是",
                    "Mid": 23558,
                    "IsVote": "否",
                    "presort": 1
                }],
                "taskColor": "tab_red"
            }, {
                "title": "华融新兴经营与投资决策委员会2018年第2次会议",
                "processName": "华融新兴经营与投资决策委员会",
                "taskName": "进行",
                "time": "2018-12-18 16:16:38",
                "otherContentList": [{
                    "totalnumber1": "1",
                    "totalnumber2": "0",
                    "Dmpid": 52506,
                    "Dmpname": "测",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23554,
                    "IsVote": "否",
                    "presort": 1
                }],
                "taskColor": "tab_red"
            }, {
                "title": "公司第三届第一次工会会员代表大会（20181218测试）",
                "processName": "职工代表大会",
                "taskName": "进行",
                "time": "2018-12-18 15:02:04",
                "otherContentList": [{
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52464,
                    "Dmpname": "表决公司第三届工会委员会委员候选人-王文杰",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 1
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52465,
                    "Dmpname": "表决公司第三届工会委员会委员候选人-郑升琴",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 2
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52466,
                    "Dmpname": "表决公司第三届工会委员会委员候选人-王  荥",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 3
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52467,
                    "Dmpname": "表决公司第三届工会委员会委员候选人-成  淼",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 4
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52468,
                    "Dmpname": "表决公司第三届工会委员会委员候选人-郭京华",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 5
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52469,
                    "Dmpname": "表决公司第三届工会委员会委员候选人-吴坤达",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 6
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52470,
                    "Dmpname": "表决公司第三届工会委员会委员候选人-张玉厚",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 7
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52471,
                    "Dmpname": "表决公司第三届工会委员会委员候选人-顾  昶",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 8
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52472,
                    "Dmpname": "表决公司第三届工会委员会委员候选人-李建共",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 9
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52473,
                    "Dmpname": "表决公司第三届工会委员会委员候选人-朱立新",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 10
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52474,
                    "Dmpname": "表决公司第三届工会委员会委员候选人-李  平",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 11
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52475,
                    "Dmpname": "表决公司第三届工会委员会委员候选人-柏  毅",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 12
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52476,
                    "Dmpname": "表决公司第三届工会委员会委员候选人-王  瑨",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 13
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52477,
                    "Dmpname": "表决公司第三届工会委员会委员候选人-丁艳玲",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 14
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52478,
                    "Dmpname": "表决公司第三届工会委员会委员候选人-梁家友",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 15
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52479,
                    "Dmpname": "表决公司第三届工会委员会委员候选人-黄  芳",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 16
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52480,
                    "Dmpname": "表决公司第三届工会委员会委员候选人-张惠萍",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 17
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52481,
                    "Dmpname": "表决公司第三届工会委员会委员候选人-崔文良",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 18
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52482,
                    "Dmpname": "表决公司第三届经费审查委员会委员候选人-成  淼",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 19
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52483,
                    "Dmpname": "表决公司第三届经费审查委员会委员候选人-马凌云",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 20
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52484,
                    "Dmpname": "表决公司第三届经费审查委员会委员候选人-曹  力",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 21
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52485,
                    "Dmpname": "表决公司第三届经费审查委员会委员候选人-洪明艳",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 22
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52486,
                    "Dmpname": "表决公司第三届经费审查委员会委员候选人-董  维",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 23
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52487,
                    "Dmpname": "表决公司第三届经费审查委员会委员候选人-郭  琦",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 24
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52488,
                    "Dmpname": "表决公司第三届经费审查委员会委员候选人-郑  燕",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 25
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52490,
                    "Dmpname": "表决公司第三届经费审查委员会委员候选人-赖晓玲",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 26
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52491,
                    "Dmpname": "表决公司第三届经费审查委员会委员候选人-蒋  政",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 27
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52492,
                    "Dmpname": "表决公司第三届女职工委员会委员候选人-郭京华",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 28
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52493,
                    "Dmpname": "表决公司第三届女职工委员会委员候选人-王  荥",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 29
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52494,
                    "Dmpname": "表决公司第三届女职工委员会委员候选人-罗华玲",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 30
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52495,
                    "Dmpname": "表决公司第三届女职工委员会委员候选人-林学勤",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 31
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52496,
                    "Dmpname": "表决公司第三届女职工委员会委员候选人-王  岚",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 32
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52497,
                    "Dmpname": "表决公司第三届女职工委员会委员候选人-刘  玲",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 33
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52498,
                    "Dmpname": "表决公司第三届女职工委员会委员候选人-黄  芳",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 34
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52499,
                    "Dmpname": "表决公司第三届女职工委员会委员候选人-靳朝晖",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 35
                }, {
                    "totalnumber1": "36",
                    "totalnumber2": "0",
                    "Dmpid": 52500,
                    "Dmpname": "表决公司第三届女职工委员会委员候选人-颜慧卿",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23552,
                    "IsVote": "否",
                    "presort": 36
                }],
                "taskColor": "tab_red"
            }, {
                "title": "公司第三届第一次职工代表大会（20181218测试） ",
                "processName": "职工代表大会",
                "taskName": "进行",
                "time": "2018-12-18 15:01:24",
                "otherContentList": [{
                    "totalnumber1": "5",
                    "totalnumber2": "0",
                    "Dmpid": 52501,
                    "Dmpname": "表决《中国华融工资管理办法（暂行）》",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23553,
                    "IsVote": "否",
                    "presort": 1
                }, {
                    "totalnumber1": "5",
                    "totalnumber2": "0",
                    "Dmpid": 52502,
                    "Dmpname": "表决《员工考勤和休假管理办法》",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23553,
                    "IsVote": "否",
                    "presort": 2
                }, {
                    "totalnumber1": "5",
                    "totalnumber2": "0",
                    "Dmpid": 52503,
                    "Dmpname": "表决《中国华融员工职务任免管理办法》",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23553,
                    "IsVote": "否",
                    "presort": 3
                }, {
                    "totalnumber1": "5",
                    "totalnumber2": "0",
                    "Dmpid": 52504,
                    "Dmpname": "表决《中国华融关键岗位人员管理办法》",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23553,
                    "IsVote": "否",
                    "presort": 4
                }, {
                    "totalnumber1": "5",
                    "totalnumber2": "0",
                    "Dmpid": 52505,
                    "Dmpname": "表决《公司第三届职工代表提案审查委员会委员名单草案》",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23553,
                    "IsVote": "否",
                    "presort": 5
                }],
                "taskColor": "tab_red"
            }, {
                "title": "科技委员会2018年第1次会议",
                "processName": "科技委员会",
                "taskName": "草稿",
                "time": "2018-12-08 08:00:00",
                "otherContentList": [],
                "taskColor": "tab_lightblue"
            }, {
                "title": "科技委员会2018年第2次会议",
                "processName": "科技委员会",
                "taskName": "草稿",
                "time": "2018-12-08 08:00:00",
                "otherContentList": [],
                "taskColor": "tab_lightblue"
            }, {
                "title": "科技委员会2018年第2次会议",
                "processName": "科技委员会",
                "taskName": "草稿",
                "time": "2018-12-07 17:00:00",
                "otherContentList": [],
                "taskColor": "tab_lightblue"
            }, {
                "title": "科技委员会2018年第3次会议",
                "processName": "科技委员会",
                "taskName": "草稿",
                "time": "2018-12-07 17:00:00",
                "otherContentList": [],
                "taskColor": "tab_lightblue"
            }, {
                "title": "科技委员会2018年第4次会议",
                "processName": "科技委员会",
                "taskName": "草稿",
                "time": "2018-12-07 17:00:00",
                "otherContentList": [],
                "taskColor": "tab_lightblue"
            }, {
                "title": "科技委员会2018年第1次会议",
                "processName": "科技委员会",
                "taskName": "结束",
                "time": "2018-12-07 11:09:30",
                "otherContentList": [],
                "taskColor": "tab_gray"
            }, {
                "title": "风险管理和内部控制委员会2018年第1次会议",
                "processName": "风险管理和内部控制委员会",
                "taskName": "进行",
                "time": "2018-11-26 17:11:59",
                "otherContentList": [{
                    "totalnumber1": "1",
                    "totalnumber2": "0",
                    "Dmpid": 30415,
                    "Dmpname": "2009年三季度风险报告",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23530,
                    "IsVote": "否",
                    "presort": 1
                }],
                "taskColor": "tab_red"
            }, {
                "title": "华融股份经营决策委员会2018年第2次会议",
                "processName": "华融股份经营决策委员会",
                "taskName": "进行",
                "time": "2018-11-06 15:21:30",
                "otherContentList": [{
                    "totalnumber1": "2",
                    "totalnumber2": "0",
                    "Dmpid": 39814,
                    "Dmpname": "内蒙古分公司对包头市荣泰置业有限责任公司3亿元结构化投资项目",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23525,
                    "IsVote": "否",
                    "presort": 1
                }, {
                    "totalnumber1": "2",
                    "totalnumber2": "0",
                    "Dmpid": 52100,
                    "Dmpname": "888测试华融股份经营决策委员会",
                    "Dmptype": "审查类",
                    "Dmpstatus": "已结束",
                    "Dmpresult": "未通过",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23525,
                    "IsVote": "否",
                    "presort": 2
                }],
                "taskColor": "tab_red"
            }, {
                "title": "职工代表大会暨工会会员代表大会2018年第1次会议",
                "processName": "职工代表大会",
                "taskName": "会前",
                "time": "2018-10-31 08:00:00",
                "otherContentList": [],
                "taskColor": "tab_blue"
            }, {
                "title": "职工代表大会暨工会会员代表大会2018年第12次会议",
                "processName": "职工代表大会",
                "taskName": "进行",
                "time": "2018-10-30 09:18:49",
                "otherContentList": [{
                    "totalnumber1": "1",
                    "totalnumber2": "0",
                    "Dmpid": 52448,
                    "Dmpname": "eee",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23518,
                    "IsVote": "否",
                    "presort": 1
                }],
                "taskColor": "tab_red"
            }, {
                "title": "国际会2018年第28次会议",
                "processName": "华融国际投资决策委员会2",
                "taskName": "进行",
                "time": "2018-10-25 13:46:57",
                "otherContentList": [{
                    "totalnumber1": "1",
                    "totalnumber2": "0",
                    "Dmpid": 52447,
                    "Dmpname": "测试签到接口呀呀呀呀呀哈哈哈哈",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23516,
                    "IsVote": "否",
                    "presort": 1
                }],
                "taskColor": "tab_red"
            }, {
                "title": "职工代表大会暨工会会员代表大会2018年第1次会议",
                "processName": "职工代表大会",
                "taskName": "进行",
                "time": "2018-10-23 14:46:18",
                "otherContentList": [{
                    "totalnumber1": "1",
                    "totalnumber2": "0",
                    "Dmpid": 52446,
                    "Dmpname": "1023",
                    "Dmptype": "审查类",
                    "Dmpstatus": "已结束",
                    "Dmpresult": "未通过",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23514,
                    "IsVote": "否",
                    "presort": 1
                }],
                "taskColor": "tab_red"
            }, {
                "title": "国际会2018年第27次会议",
                "processName": "华融国际投资决策委员会2",
                "taskName": "进行",
                "time": "2018-10-18 10:24:56",
                "otherContentList": [{
                    "totalnumber1": "1",
                    "totalnumber2": "0",
                    "Dmpid": 52445,
                    "Dmpname": "测试一下空文档",
                    "Dmptype": "审查类",
                    "Dmpstatus": "进行中",
                    "Dmpresult": "",
                    "DmpSecerit": "普通",
                    "VoteVisible": "否",
                    "Mid": 23512,
                    "IsVote": "否",
                    "presort": 1
                }],
                "taskColor": "tab_red"
            }]
        };
    },
    methods: {
        itemClick(item) {
            alert(item.title);
        }
    },
    components: {
        HListNew
    }
};
</script>

<style lang="less">
.detailList{
    font-size: 14px;
    color: #606266;
    line-height: 24px;
    overflow: hidden;
    display: -webkit-box;
    -webkit-line-clamp: 1;
    -webkit-box-orient: vertical;
}
</style>


